### ISSUE TITLE
小程序支付问题

### ISSUE THREAD

**Issue by sensen1991** [gooking/wxapi#1]
你好，小程序支付时报如下错误：
请求地址：https://api.it120.cc/8e5c077bddd72370064a45fdbe565bd1/pay/wx/wxapp
请求参数：
token:473d0122-4488-4b60-89d4-a2d88c15e770
money:9
remark:支付订单 ：246483
payName:在线支付
nextAction:{"type":0,"id":246483}
返回错误：
{"code":50000,"msg":"mch_id参数格式错误"}
文档里没这个错误，请帮忙看下，多谢

**Comment by gooking** [comment]
后台，微信设置，填写正确的微信支付商户号，这是你商户号没填或者填错了


发自我的 iPhone

**Comment by sensen1991** [comment]
我是个体小程序，不能申请商户号【尴尬】

**Comment by gooking** [comment]
个体户也可以申请的

**Comment by sensen1991** [comment]
额，说错了。。，我是个人（开发者），不是个体
